import requests
import time
from typing import List, Dict, Any

class SigNozClient:
    def __init__(self, host: str = "http://localhost:8080", api_key: str = None):
        self.host = host.rstrip("/")
        self.headers = {}
        if api_key:
            self.headers["SIGNOZ-API-KEY"] = api_key

    def fetch_recent_spans(self, service_name: str = "LocalAgent1", time_window_minutes: int = 15) -> List[Dict[str, Any]]:
        """Queries SigNoz for recent spans generated by the target agent."""
        end_time_ms = int(time.time() * 1000)
        start_time_ms = end_time_ms - (time_window_minutes * 60 * 1000)

        # SigNoz Trace Query Payload
        payload = {
            "start": start_time_ms,
            "end": end_time_ms,
            "compositeQuery": {
                "queryType": "builder",
                "builderQueries": {
                    "A": {
                        "dataSource": "traces",
                        "queryName": "A",
                        "aggregateOperator": "noop",
                        "filters": {
                            "items": [
                                {
                                    "key": {"key": "serviceName", "type": "tag"},
                                    "op": "=",
                                    "value": service_name
                                }
                            ],
                            "op": "AND"
                        },
                        "limit": 100
                    }
                }
            }
        }

        try:
            url = f"{self.host}/api/v3/query_range"
            res = requests.post(url, json=payload, headers=self.headers, timeout=5)
            if res.status_code == 200:
                data = res.json()
                # Parse trace payload matrix
                result_matrix = data.get("result", [])
                if result_matrix and len(result_matrix) > 0:
                    return result_matrix[0].get("list", [])
            return []
        except Exception as e:
            # Fallback for offline/mock scenario during quick testing
            print(f"⚠️ [SigNoz API Warning]: Could not reach query engine ({e}).")
            return []